"$schema" = 'https://starship.rs/config-schema.json'

[os]
disabled = false
format = "$symbol "
symbols.Windows = ""

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'
