#! /usr/bin/env bash

if [ $# -eq 0 ]; then
    dir_to_open="$(find ~ -type d | fzf)"
else
    dir_to_open="$(find "$1" -type d | fzf)"
fi

if [ -n "$dir_to_open" ]; then
    dolphin "$dir_to_open" &>/dev/null &
fi
