#!/usr/bin/env bash

if  sensors &> /dev/null
then
    sensordata=$(sensors)
    memorydata=$(free -h)
    echo "$sensordata" | awk '/^CPU:/{print}'
    echo "$memorydata" | awk '/^Mem:/{print "Memory:      "$3 "/" $2}'
    echo "$sensordata" | awk '/^Processor Fan:/{print} /^Video Fan:/{print}'
fi
