#!/usr/bin/env bash

movies_path="/run/media/nidzo/DATA/media"

podman run \
    --rm \
    --detach \
    --label "io.containers.autoupdate=registry" \
    --name myjellyfin \
    --publish 8096:8096/tcp \
    --volume /home/nidzo/.config/jellyfin/cache:/cache:Z \
    --volume /home/nidzo/.config/jellyfin/config:/config:Z \
    --volume "$movies_path":/media:ro \
    docker.io/jellyfin/jellyfin:latest
