#!/usr/bin/env bash

start_jellyfin() {

    data_path="/run/user/1000/kio-fuse-"*"/smb/fritz.box/FRITZ.NAS/DATA"

    movies_path="$(realpath $data_path)/jellyfin_media"

    podman run \
        --rm \
        --detach \
        --label "io.containers.autoupdate=registry" \
        --name myjellyfin \
        --publish 8096:8096/tcp \
        --volume /home/nidzo/.config/jellyfin/cache:/cache:Z \
        --volume /home/nidzo/.config/jellyfin/config:/config:Z \
        --volume "$movies_path":/media:ro \
        docker.io/jellyfin/jellyfin:latest
}

start_jellyfin
